[filter_scheduler]
enabled_filters = RetryFilter,AvailabilityZoneFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,PciPassthroughFilter
available_filters = nova.scheduler.filters.all_filters

[pci]
# Same aliases as compute and scheduler
alias = {"device_type": "type-PCI", "name": "quadro_p2200", "product_id": "1c31", "vendor_id": "10de"}
alias = {"device_type": "type-PF", "name": "t4", "product_id": "1eb8", "vendor_id": "10de"}