[filter_scheduler]
enabled_filters = ComputeFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,PciPassthroughFilter

[pci]
# Same aliases as compute node
alias = {"device_type": "type-PCI", "name": "quadro_p2200", "product_id": "1c31", "vendor_id": "10de"}
alias = {"device_type": "type-PF", "name": "t4", "product_id": "1eb8", "vendor_id": "10de"}