network:
  version: 2
  renderer: networkd
  ethernets:
    eth0-host:
      match:
        macaddress: "90:5a:08:0f:f3:dd"
      optional: true
      addresses:
      - "10.0.51.6/27"
      nameservers:
        addresses:
        - 10.0.51.1
        search:
        - localdomain
      dhcp4: false
      dhcp6: false
      set-name: "eth0-host"
      routes:
      - to: "default"
        via: "10.0.51.1"
    eth1-mgmt:
      match:
        macaddress: "9c:69:b4:65:ea:94"
      optional: true
      addresses:
      - "10.0.51.40/27"
      nameservers:
        addresses:
        - 10.0.51.33
        search:
        - localdomain
      dhcp4: false
      dhcp6: false
      set-name: "eth1-mgmt"
      routes:
      - scope: "link"
        table: 101
        to: "10.0.51.32/27"
      - table: 101
        to: "default"
        via: "10.0.51.33"
      routing-policy:
      - table: 101
        from: "10.0.51.40/32"
      wakeonlan: false
    eth3-tenant:
      match:
        macaddress: "9c:69:b4:65:ea:96"
      dhcp4: false
      dhcp6: false
      set-name: "eth3-tenant"
      wakeonlan: false
    eth2-ceph:
      match:
        macaddress: "9c:69:b4:65:ea:95"
      optional: true
      addresses:
      - "10.0.51.71/27"
      nameservers:
        addresses:
        - 10.0.51.33
        search:
        - localdomain
      dhcp4: false
      dhcp6: false
      set-name: "eth2-ceph"
    eno2:
      optional: true
      dhcp4: true
  bridges:
    br-provider:
      interfaces:
      - eth3-tenant.57
  vlans:
    eth1-mgmt.54:
      addresses:
      - "10.0.54.6/24"
      dhcp4: false
      dhcp6: false
      id: 54
      link: "eth1-mgmt"
    eth1-mgmt.55:
      addresses:
      - "10.0.55.6/24"
      dhcp4: false
      dhcp6: false
      id: 55
      link: "eth1-mgmt"
    eth3-tenant.57:
      dhcp4: false
      dhcp6: false
      id: 57
      link: "eth3-tenant"
